=== simeonradivoev/gameflow-store/schema/emulator.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "homepage": {
      "type": "string",
      "format": "uri"
    },
    "logo": {
      "type": "string",
      "format": "uri"
    },
    "license": {
      "type": "object",
      "properties": {
        "identifier": {
          "type": "string"
        },
        "url": {
          "type": "string",
          "format": "uri"
        }
      }
    },
    "bios": {
      "type": "string",
      "enum": [
        "required",
        "optional"
      ]
    },
    "repository": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "git"
          ]
        },
        "url": {
          "type": "string",
          "format": "uri"
        }
      }
    },
    "downloads": {
      "type": "object",
      "patternProperties": {
        "^(?:(aix|darwin|freebsd|linux|openbsd|sunos|win32|android):(arm|arm64|ia32|mips|mipsel|ppc|ppc64|s390|s390x|x32|x64))*$": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "type": "object",
                "properties": {
                  "type": {
                    "const": "github"
                  },
                  "host": {
                    "type": "string",
                    "format": "uri"
                  },
                  "bin": {
                    "type": "string"
                  },
                  "pattern": {
                    "type": "string"
                  },
                  "path": {
                    "type": "string"
                  }
                },
                "required": [
                  "path",
                  "pattern"
                ]
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "const": "direct"
                  },
                  "url": {
                    "type": "string",
                    "format": "uri"
                  },
                  "bin": {
                    "type": "string"
                  }
                },
                "required": [
                  "url"
                ]
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "const": "scoop"
                  },
                  "url": {
                    "type": "string",
                    "format": "uri"
                  }
                },
                "required": [
                  "url"
                ]
              }
            ],
            "unevaluatedProperties": false,
            "required": [
              "type"
            ]
          }
        }
      },
      "additionalProperties": false
    },
    "aliases": {
      "type": "object",
      "properties": {
        "winget": {
          "type": "string"
        },
        "scoop": {
          "type": "string"
        },
        "flatpak": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "type": {
      "type": "string",
      "enum": [
        "emulator"
      ]
    },
    "systems": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "os": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "keywords": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "funding": {
      "type": "string",
      "format": "uri"
    },
    "notes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "name",
    "description",
    "logo",
    "license",
    "type"
  ],
  "additionalProperties": false
}

=== simeonradivoev/gameflow-store/buckets/emulators/XENIA.json
{
    "name": "XENIA-EDGE",
    "description": "Xenia Edge is yet another experimental fork of the Xenia emulator, mainly based on Xenia Canary but with the aim of quicker iteration and improvements to Vulkan backend and Linux platform in particular. Windows of course remains fully supported as well and will benefit from changes made here especially with its Vulkan backend.",
    "homepage": "https://xenia.jp",
    "logo": "https://xenia.jp/images/logo-256x256.png",
    "license": {
        "identifier": "BSD-3-Clause",
        "url": "https://github.com/xenia-project/xenia/blob/master/LICENSE"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/xenia-project/xenia.git"
    },
    "downloads": {
        "win32:x64": [
            {
                "type": "github",
                "path": "xenia-project/release-builds-windows",
                "pattern": "xenia_master.zip"
            }
        ]
    },
    "aliases": {
        "winget": "xenia-project.xenia",
        "scoop": "games/xenia"
    },
    "type": "emulator",
    "systems": [
        "xbox360"
    ],
    "os": [
        "win32"
    ]
}

=== simeonradivoev/gameflow-store/buckets/emulators/DUCKSTATION.json
{
    "name": "DUCKSTATION",
    "description": "DuckStation is a PS1 Emulator aiming for the best accuracy and game support.",
    "homepage": "https://www.duckstation.org/",
    "logo": "https://www.duckstation.org/assets/img/duck_head.svg",
    "license": {
        "identifier": "CC-BY-NC-ND-4.0",
        "url": "https://github.com/stenzek/duckstation/blob/master/LICENSE"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/stenzek/duckstation.git"
    },
    "downloads": {
        "win32:x64": [
            {
                "type": "github",
                "path": "stenzek/duckstation",
                "pattern": "duckstation-windows-x64-release.zip"
            }
        ],
        "win32:arm64": [
            {
                "type": "github",
                "path": "stenzek/duckstation",
                "pattern": "duckstation-windows-arm64-release.zip"
            }
        ],
        "linux:x64": [
            {
                "type": "github",
                "path": "stenzek/duckstation",
                "pattern": "DuckStation-x64.AppImage"
            }
        ],
        "linux:arm64": [
            {
                "type": "github",
                "path": "stenzek/duckstation",
                "pattern": "DuckStation-arm64.AppImage"
            }
        ]
    },
    "aliases": {
        "winget": "Stenzek.DuckStation",
        "scoop": "games/duckstation"
    },
    "type": "emulator",
    "systems": [
        "psx"
    ],
    "os": [
        "win32",
        "linux",
        "darwin"
    ]
}

=== simeonradivoev/gameflow-store/buckets/emulators/PCSX2.json
{
    "name": "PCSX2",
    "homepage": "https://pcsx2.net/",
    "description": "PCSX2 is a free and open-source PlayStation 2 (PS2) emulator. Its purpose is to emulate the PS2's hardware, using a combination of MIPS CPU Interpreters, Recompilers, and a Virtual Machine that manages hardware states and system memory.",
    "license": {
        "identifier": "GPL-3.0",
        "url": "https://github.com/PCSX2/pcsx2/blob/master/COPYING.GPLv3"
    },
    "notes": [
        "ATTENTION: PCSX2 requires a dump of the PS2 BIOS to function.",
        "Place the BIOS file in $persist_dir\\bios",
        "Learn more at https://wiki.pcsx2.net/Setting_up_Windows_version#BIOS"
    ],
    "funding": "https://github.com/sponsors/PCSX2",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/2/2b/PCSX2_logo4.png",
    "repository": {
        "type": "git",
        "url": "https://github.com/PCSX2/pcsx2.git"
    },
    "downloads": {
        "win32,linux": {
            "type": "github",
            "url": "https://github.com/PCSX2/pcsx2"
        }
    },
    "aliases": {
        "winget": "pcsx2",
        "scoop": "games/pcsx2",
        "flatpak": "net.pcsx2.PCSX2"
    },
    "type": "emulator",
	"systems": [
		"ps2"
	],
    "os": [
        "darwin",
        "linux",
        "win32"
    ],
    "keywords": [
        "emulator",
        "cpp",
        "emulation",
        "pcsx2",
        "ps2"
    ]
}

=== simeonradivoev/gameflow-store/buckets/emulators/CEMU.json
{
    "name": "CEMU",
    "description": "Nintendo GameCube and Wii emulator, with enhancements and Netplay",
    "homepage": "https://cemu.info/",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/9/9e/Cemu_Emulator_Official_Logo.png",
    "license": {
        "identifier": "MPL-2.0",
        "url": "https://github.com/cemu-project/Cemu/blob/main/LICENSE.txt"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/cemu-project/Cemu.git"
    },
    "downloads": {
        "win32:x64": [
            {
                "type": "github",
                "path": "cemu-project/Cemu",
                "pattern": "cemu-*-windows-x64.zip"
            },
            {
                "type": "scoop",
                "url": "https://cdn.jsdelivr.net/gh/Calinou/scoop-games@master/bucket/cemu.json"
            }
        ],
        "linux:x64": [
            {
                "type": "github",
                "path": "cemu-project/Cemu",
                "pattern": "Cemu-*-x86_64.AppImage"
            }
        ]
    },
    "keywords": [
        "cemu",
        "emulation",
        "cpp",
        "nintendo",
        "wiiu"
    ],
    "aliases": {
        "winget": "Cemu.Cemu",
        "scoop": "games/cemu",
        "flatpak": "info.cemu.Cemu"
    },
    "type": "emulator",
    "systems": [
        "wiiu"
    ],
    "os": [
        "win32",
        "linux",
        "darwin"
    ]
}
