=== simeonradivoev/gameflow-store/schema/emulator.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "homepage": {
      "type": "string",
      "format": "uri"
    },
    "logo": {
      "type": "string",
      "format": "uri"
    },
    "license": {
      "type": "object",
      "properties": {
        "identifier": {
          "type": "string"
        },
        "url": {
          "type": "string",
          "format": "uri"
        }
      }
    },
    "bios": {
      "type": "string",
      "enum": [
        "required",
        "optional"
      ]
    },
    "repository": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "git"
          ]
        },
        "url": {
          "type": "string",
          "format": "uri"
        }
      }
    },
    "downloads": {
      "type": "object",
      "patternProperties": {
        "^(?:(aix|darwin|freebsd|linux|openbsd|sunos|win32|android):(arm|arm64|ia32|mips|mipsel|ppc|ppc64|s390|s390x|x32|x64))*$": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "type": "object",
                "properties": {
                  "type": {
                    "const": "github"
                  },
                  "host": {
                    "type": "string",
                    "format": "uri"
                  },
                  "bin": {
                    "type": "string"
                  },
                  "pattern": {
                    "type": "string"
                  },
                  "path": {
                    "type": "string"
                  }
                },
                "required": [
                  "path",
                  "pattern"
                ]
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "const": "direct"
                  },
                  "url": {
                    "type": "string",
                    "format": "uri"
                  },
                  "bin": {
                    "type": "string"
                  }
                },
                "required": [
                  "url"
                ]
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "const": "scoop"
                  },
                  "url": {
                    "type": "string",
                    "format": "uri"
                  }
                },
                "required": [
                  "url"
                ]
              }
            ],
            "unevaluatedProperties": false,
            "required": [
              "type"
            ]
          }
        }
      },
      "additionalProperties": false
    },
    "aliases": {
      "type": "object",
      "properties": {
        "winget": {
          "type": "string"
        },
        "scoop": {
          "type": "string"
        },
        "flatpak": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "type": {
      "type": "string",
      "enum": [
        "emulator"
      ]
    },
    "systems": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "os": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "keywords": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "funding": {
      "type": "string",
      "format": "uri"
    },
    "notes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "name",
    "description",
    "logo",
    "license",
    "type"
  ],
  "additionalProperties": false
}

=== simeonradivoev/gameflow-store/buckets/emulators/XENIA-EDGE.json
{
    "name": "XENIA",
    "description": "Xenia is an open source research project for emulating Xbox 360 games on modern PCs.",
    "homepage": "https://xenia.jp",
    "logo": "https://raw.githubusercontent.com/xenia-canary/xenia/master/assets/icon/256.png",
    "license": {
        "identifier": "BSD-3-Clause",
        "url": "https://github.com/has207/xenia-edge/blob/edge/LICENSE"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/has207/xenia-edge.git"
    },
    "downloads": {
        "win32,linux": {
            "type": "github",
            "url": "https://github.com/has207/xenia-edge"
        }
    },
    "aliases": {
        "scoop": "games/xenia-edge"
    },
    "type": "emulator",
    "systems": [
        "xbox360"
    ],
    "os": [
        "win32"
    ]
}

=== simeonradivoev/gameflow-store/buckets/emulators/XEMU.json
{
    "name": "XEMU",
    "description": "A free and open-source application that emulates the original Microsoft Xbox game console. Supports connecting up to 4 controllers for local play, networking for multiplayer, resolution scaling, and more.",
    "homepage": "https://xemu.app/",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Xemu_logo_green.svg",
    "license": {
        "identifier": "GPL-2.0",
        "url": "https://github.com/xemu-project/xemu/blob/master/LICENSE"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/xemu-project/xemu.git"
    },
    "downloads": {
        "win32": {
            "type": "github",
            "url": "https://github.com/xemu-project/xemu"
        }
    },
    "aliases": {
        "winget": "xemu-project.xemu",
        "scoop": "games/xemu",
        "flatpak": "app.xemu.xemu"
    },
    "type": "emulator",
    "systems": [
		"xbox"
	],
    "os": [
        "win32",
        "linux",
        "darwin"
    ]
}

=== simeonradivoev/gameflow-store/buckets/emulators/UMU.json
{
    "name": "UMU",
    "description": "Unified launcher for Windows games on Linux. It is essentially a copy of the Steam Runtime Tools and Steam Linux Runtime that Valve uses for Proton, with some modifications made so that it can be used outside of Steam.",
    "homepage": "https://github.com/Open-Wine-Components/umu-launcher",
    "logo": "https://avatars.githubusercontent.com/u/119976475",
    "license": {
        "identifier": "GPL-3.0",
        "url": "https://github.com/Open-Wine-Components/umu-launcher/blob/main/LICENSE"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/Open-Wine-Components/umu-launcher.git"
    },
    "downloads": {
        "linux:x64": [
            {
                "type": "github",
                "path": "Open-Wine-Components/umu-launcher",
                "pattern": "umu-launcher-*-zipapp.tar"
            }
        ]
    },
    "aliases": {
    },
    "type": "emulator",
    "systems": [
        "win"
    ],
    "os": [
        "linux"
    ]
}

=== simeonradivoev/gameflow-store/buckets/emulators/PPSSPP.json
{
    "name": "PPSSPP",
    "description": "PPSSPP is a free and open-source PSP emulator for Windows, macOS, Linux, iOS, Android, Nintendo Wii U, Nintendo Switch, BlackBerry 10, MeeGo, Pandora, Xbox Series X/S and Symbian with a focus on speed and portability",
    "homepage": "https://www.ppsspp.org/",
    "logo": "https://www.ppsspp.org/static/img/platform/ppsspp-icon.png",
    "license": {
        "identifier": "GPL-2.0-or-later",
        "url": "https://github.com/hrydgard/ppsspp/blob/master/LICENSE.TXT"
    },
    "keywords": [
        "psp",
        "emulation",
        "emulator",
        "playstationportable",
        "playstation-portable",
        "umd",
        "universalmediadisc",
        "universal-media-disc"
    ],
    "repository": {
        "type": "git",
        "url": "https://github.com/hrydgard/ppsspp.git"
    },
    "downloads": {
        "win32:x64": [
            {
                "type": "github",
                "path": "hrydgard/ppsspp",
                "pattern": "PPSSPP-*-Windows-x64.zip"
            }
        ],
        "win32:arm64": [
            {
                "type": "github",
                "path": "hrydgard/ppsspp",
                "pattern": "PPSSPP-*-Windows-ARM64.zip"
            }
        ],
        "linux:x64": [
            {
                "type": "github",
                "path": "hrydgard/ppsspp",
                "pattern": "PPSSPP-*-anylinux-x86_64.AppImage"
            }
        ],
        "linux:arm64": [
            {
                "type": "github",
                "path": "hrydgard/ppsspp",
                "pattern": "PPSSPP-*-anylinux-aarch64.AppImage"
            }
        ]
    },
    "aliases": {
        "winget": "PPSSPPTeam.PPSSPP",
        "scoop": "games/ppsspp",
        "flatpak": "org.ppsspp.PPSSPP"
    },
    "type": "emulator",
    "systems": [
        "psp"
    ],
    "os": [
        "win32",
        "darwin",
        "linux"
    ]
}

=== simeonradivoev/gameflow-store/buckets/emulators/RYUJINX.json
{
    "name": "RYUJINX",
    "description": "Nintendo Switch 1 emulator written in C#.",
    "homepage": "https://ryujinx.app/",
    "logo": "https://raw.githubusercontent.com/Ryubing/Assets/refs/heads/main/RyujinxApp_1024.png",
    "license": {
        "identifier": "MIT",
        "url": "https://git.ryujinx.app/ryubing/ryujinx/-/blob/master/LICENSE.txt"
    },
    "repository": {
        "type": "git",
        "url": "https://git.ryujinx.app/ryubing/ryujinx.git"
    },
    "downloads": {
        "win32:x64": [
            {
                "type": "gitlab",
                "path": "ryubing/ryujinx",
                "pattern": "ryujinx-*-win_x64.zip"
            }
        ],
        "linux:x64": [
            {
                "type": "gitlab",
                "path": "ryubing/ryujinx",
                "pattern": "ryujinx-*-x64.AppImage"
            }
        ],
        "linux:arm64": [
            {
                "type": "gitlab",
                "path": "ryubing/ryujinx",
                "pattern": "ryujinx-*-arm64.AppImage"
            }
        ]
    },
    "notes": [
        "ATTENTION: Ryujinx requires Nintendo Switch firmware and a prod.keys file to function.",
        "Learn more at https://git.ryujinx.app/ryubing/ryujinx/-/wikis/FAQ-&-Troubleshooting"
    ],
    "aliases": {
        "scoop": "games/ryujinx",
        "flatpak": "io.github.ryubing.Ryujinx"
    },
    "type": "emulator",
    "bios": "required",
    "systems": [
        "switch"
    ],
    "os": [
        "win32",
        "linux",
        "darwin"
    ]
}

=== simeonradivoev/gameflow-store/buckets/emulators/AZAHAR.json
{
    "name": "AZAHAR",
    "description": "An open-source 3DS emulator project based on Citra.",
    "homepage": "https://azahar-emu.org/",
    "logo": "https://azahar-emu.org/resources/images/logo/azahar-logo.svg",
    "license": {
        "identifier": "GPL-2.0",
        "url": "https://github.com/azahar-emu/azahar/blob/master/license.txt"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/azahar-emu/azahar.git"
    },
    "downloads": {
        "win32:x64": [
            {
                "type": "github",
                "path": "azahar-emu/azahar",
                "pattern": "azahar-*-windows-msvc.zip"
            }
        ],
        "linux:x64": [
            {
                "type": "github",
                "path": "azahar-emu/azahar",
                "pattern": "azahar-wayland.AppImage"
            }
        ]
    },
    "aliases": {
        "winget": "AzaharEmu.Azahar",
        "scoop": "games/azahar",
        "flatpak": "org.azahar_emu.Azahar"
    },
    "type": "emulator",
    "bios": "required",
    "systems": [
        "3ds"
    ],
    "os": [
        "win32",
        "linux",
        "darwin",
        "android"
    ]
}

=== simeonradivoev/gameflow-store/buckets/emulators/RPCS3.json
{
    "name": "RPCS3",
    "description": "RPCS3 is a multi-platform open-source Sony PlayStation 3 emulator and debugger written in C++ for Windows, Linux, macOS and FreeBSD.",
    "homepage": "https://rpcs3.net/",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/c/c5/RPCS3_logo.png",
    "license": {
        "identifier": "GPL-2.0",
        "url": "https://github.com/RPCS3/rpcs3/blob/master/LICENSE"
    },
    "keywords": [
        "c",
        "emulation",
        "emulator",
        "opengl",
        "playstation3",
        "ps3",
        "multiplatform"
    ],
    "repository": {
        "type": "git",
        "url": "https://github.com/RPCS3/rpcs3.git"
    },
    "downloads": {
        "win32:x64": [
            {
                "type": "github",
                "path": "RPCS3/rpcs3-binaries-win",
                "pattern": "rpcs3-*_win64_msvc.7z"
            },
            {
                "type": "scoop",
                "url": "https://cdn.jsdelivr.net/gh/Calinou/scoop-games@latest/bucket/rpcs3.json"
            }
        ],
        "win32:arm64": [
            {
                "type": "github",
                "path": "RPCS3/rpcs3-binaries-win-arm64",
                "pattern": "rpcs3-*_win64_aarch64_clang.7z "
            },
            {
                "type": "scoop",
                "url": "https://cdn.jsdelivr.net/gh/Calinou/scoop-games@latest/bucket/rpcs3.json"
            }
        ],
        "linux:x64": [
            {
                "type": "github",
                "path": "RPCS3/rpcs3-binaries-linux",
                "pattern": "rpcs3-*_linux64.AppImage"
            }
        ],
        "linux:arm64": [
            {
                "type": "github",
                "path": "RPCS3/rpcs3-binaries-linux-arm64",
                "pattern": "rpcs3-*_linux_aarch64.AppImage"
            }
        ],
        "darwin:x64": [
            {
                "type": "github",
                "path": "RPCS3/rpcs3-binaries-mac",
                "pattern": "rpcs3-*_macos.7z"
            }
        ],
        "darwin:arm64": [
            {
                "type": "github",
                "path": "RPCS3/rpcs3-binaries-mac-arm64",
                "pattern": "rpcs3-*_macos_aarch64.7z"
            }
        ]
    },
    "aliases": {
        "winget": "PPSSPPTeam.PPSSPP",
        "scoop": "games/rpcs3",
        "flatpak": "net.rpcs3.RPCS3"
    },
    "type": "emulator",
    "bios": "required",
    "systems": [
        "ps3"
    ],
    "os": [
        "win32",
        "darwin",
        "linux"
    ]
}

=== simeonradivoev/gameflow-store/buckets/emulators/DOLPHIN.json
{
    "name": "DOLPHIN",
    "description": "Dolphin is an emulator for two recent Nintendo video game consoles: the GameCube and the Wii. It allows PC gamers to enjoy games for these two consoles in full HD (1080p) with several enhancements: compatibility with all PC controllers, turbo speed, networked multiplayer, and even more! ",
    "homepage": "https://dolphin-emu.org/",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/5/53/Dolphin_Emulator_Logo_Refresh.svg",
    "license": {
        "identifier": "GPL-2.0-or-later",
        "url": "https://github.com/dolphin-emu/dolphin/blob/master/COPYING"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/dolphin-emu/dolphin.git"
    },
    "keywords": ["cemu", "emulation", "cpp", "nintendo", "wiiu"],
    "aliases": {
        "winget": "DolphinEmulator.Dolphin",
        "scoop": "games/dolphin",
        "flatpak": "org.DolphinEmu.dolphin-emu"
    },
    "type": "emulator",
    "systems": [
		"gc",
        "wii"
	],
    "os": [
        "win32",
        "linux",
        "darwin"
    ]
}
